# ??????
server.port=${PORT:8080}

# ???????? ?????????? DATABASE_PUBLIC_URL (?????? ??? ????????????!)
spring.datasource.url=jdbc:postgresql://eclwbktyxozelrclshlz.supabase.co:6543/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=rx0ZNi6WZPPqJBOb
spring.datasource.driver-class-name=org.postgresql.Driver



spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ????????? H2
spring.h2.console.enabled=false
